In [174]:
# Multiple Linear Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [175]:
# Importing the dataset
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values
dataset.head(2)

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [176]:
X[:1]

array([[165349.2, 136897.8, 471784.1, 'New York']], dtype=object)

In [177]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()
X.data.obj[1]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
       1.5137759e+05, 4.4389853e+05])

In [178]:
# Avoiding the Dummy Variable Trap
X = X[:, 1:]
X.data.obj[1]

array([     0.  ,      0.  , 162597.7 , 151377.59, 443898.53])

In [179]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [180]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred[:3]

array([103015.20159796, 132582.27760815, 132447.73845175])

In [181]:
#Prediction Error
#MAPE ( Mean absolute percentage error)
y_true, y_pred = np.array(y_test), np.array(y_pred)
np.mean(np.abs((y_true - y_pred) / y_true))*100

6.449754085355757